name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: agatshop
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/agatshop/prestashop .
          docker push gcr.io/agatshop/prestashop

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy agatshop \
            --image gcr.io/agatshop/prestashop \
            --platform managed \
            --region ${{ secrets.$GOOGLE_REGION }} \
            --allow-unauthenticated
